#!/bin/bash

cp -fv /opt/github.com/simon.services/hello-world/consul.d/helloworld.json /opt/github.com/simon.services/consul/consul.d/
/opt/github.com/simon.services/consul/bin/consul reload
supervisorctl update helloworld-proxy
